name: Ruby

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          rubygems: latest # runs 'gem update --system'
      - name: Run test
        run: bundle exec rspec
